// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO2SPGmtGlWz_3a5g_1KVSE8SxaNSxI4Q',
    appId: '1:46106613533:web:9a23339d79808d4baeb3f4',
    messagingSenderId: '46106613533',
    projectId: 'joyufulapp',
    authDomain: 'joyufulapp.firebaseapp.com',
    storageBucket: 'joyufulapp.firebasestorage.app',
    measurementId: 'G-CEH7LZRH1R',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALnk1-7Cq14-fD4TJJCQ0HSqKeMz-cyfg',
    appId: '1:46106613533:ios:be1c9e1fceff9aa0aeb3f4',
    messagingSenderId: '46106613533',
    projectId: 'joyufulapp',
    storageBucket: 'joyufulapp.firebasestorage.app',
    iosBundleId: 'com.example.wordpressAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO2SPGmtGlWz_3a5g_1KVSE8SxaNSxI4Q',
    appId: '1:46106613533:web:67c718e6b9b38378aeb3f4',
    messagingSenderId: '46106613533',
    projectId: 'joyufulapp',
    authDomain: 'joyufulapp.firebaseapp.com',
    storageBucket: 'joyufulapp.firebasestorage.app',
    measurementId: 'G-JQDDMZKHP7',
  );
}
