// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBtPWc9FiE4wGjTISg9K8TmBFTVKtClBY',
    appId: '1:1000950432361:web:3e5157c60e1a17956898f8',
    messagingSenderId: '1000950432361',
    projectId: 'apphen-22',
    authDomain: 'apphen-22.firebaseapp.com',
    storageBucket: 'apphen-22.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUyI3fN77PduG0UnUeZKzeIcPxGjnYq00',
    appId: '1:1000950432361:ios:9c773a872f770ee06898f8',
    messagingSenderId: '1000950432361',
    projectId: 'apphen-22',
    storageBucket: 'apphen-22.firebasestorage.app',
    iosBundleId: 'com.example.wordpressAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBtPWc9FiE4wGjTISg9K8TmBFTVKtClBY',
    appId: '1:1000950432361:web:984b7a0d968bc2d46898f8',
    messagingSenderId: '1000950432361',
    projectId: 'apphen-22',
    authDomain: 'apphen-22.firebaseapp.com',
    storageBucket: 'apphen-22.firebasestorage.app',
  );

}